// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSr_VRbhFbefXP-6xS8n3UudnrvqWFtwI',
    appId: '1:944387183218:web:fd000040a7c877dbade8eb',
    messagingSenderId: '944387183218',
    projectId: 'fareshare-88cd9',
    authDomain: 'fareshare-88cd9.firebaseapp.com',
    storageBucket: 'fareshare-88cd9.firebasestorage.app',
    measurementId: 'G-QBJFM345YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9T-eQcwRwvXhEinYBFyHIcPJ3NKMbTk',
    appId: '1:944387183218:android:fe79e98454981bd1ade8eb',
    messagingSenderId: '944387183218',
    projectId: 'fareshare-88cd9',
    storageBucket: 'fareshare-88cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM8eFAjQzzlY0OTonD7t-b2Yzj5cI8Ry8',
    appId: '1:944387183218:ios:c3a2d75d007e686eade8eb',
    messagingSenderId: '944387183218',
    projectId: 'fareshare-88cd9',
    storageBucket: 'fareshare-88cd9.firebasestorage.app',
    iosBundleId: 'com.example.fairshare',
  );
}
